import type { CoachRecord } from '@/lib/types';

export const MOCK_COACHES: (CoachRecord & { similarity?: number; chapter_name?: string })[] = [
  {
    id: '1',
    profile_id: null,
    chapter_id: 'usa',
    chapter_name: 'WIAL USA',
    full_name: 'Craig Senecal',
    photo_url: null,
    certification_level: 'SALC',
    certification_date: '2022-03-15',
    certification_expiry: '2024-03-15',
    bio_raw: 'I coach Fortune 500 executives through organizational change.',
    bio_enhanced:
      'Craig Senecal is a SALC-certified Action Learning coach with 15+ years of experience partnering with Fortune 500 executives across North America. He specializes in organizational change management, leadership transformation, and building high-performance C-suite teams. Craig has guided over 200 senior leaders through complex strategic pivots in industries ranging from financial services to healthcare.',
    location_city: 'Washington DC',
    location_country: 'United States',
    specializations: ['corporate leadership', 'change management', 'executive coaching', 'fortune 500', 'organizational development'],
    contact_email: 'craig@wial-usa.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: 'https://linkedin.com/in/craigsenecal',
    website_url: null,
    highlight: 'I help C-suite leaders turn organizational complexity into strategic clarity through structured Action Learning.',
    total_session_hours: 145,
    total_ce_credits: 32,
  },
  {
    id: '2',
    profile_id: null,
    chapter_id: 'usa',
    chapter_name: 'WIAL USA',
    full_name: 'Bea Carson',
    photo_url: null,
    certification_level: 'SALC',
    certification_date: '2021-06-10',
    certification_expiry: '2023-06-10',
    bio_raw: 'I focus on healthcare leadership and hospital administration.',
    bio_enhanced:
      'Bea Carson is a SALC-certified Action Learning coach specializing in healthcare leadership and hospital administration. Based in New York, she works with nurse leadership teams, hospital administrators, and patient care coordinators to build collaborative problem-solving cultures. Bea has supported 40+ healthcare institutions across the tri-state area in improving leadership effectiveness and patient outcomes.',
    location_city: 'New York',
    location_country: 'United States',
    specializations: ['healthcare leadership', 'hospital administration', 'nurse leadership', 'patient care', 'team dynamics'],
    contact_email: 'bea.carson@wial-usa.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: 'Transforming healthcare teams through evidence-based Action Learning facilitation.',
    total_session_hours: 98,
    total_ce_credits: 24,
  },
  {
    id: '3',
    profile_id: null,
    chapter_id: 'usa',
    chapter_name: 'WIAL USA',
    full_name: 'James Mitchell',
    photo_url: null,
    certification_level: 'CALC',
    certification_date: '2023-09-01',
    certification_expiry: '2025-09-01',
    bio_raw: 'Education sector coach working with universities.',
    bio_enhanced:
      'James Mitchell is a CALC-certified Action Learning coach dedicated to the education sector. Based in Chicago, he collaborates with university leadership teams, academic program directors, and faculty groups to enhance collaborative decision-making and academic innovation. James brings deep expertise in higher education administration and faculty development.',
    location_city: 'Chicago',
    location_country: 'United States',
    specializations: ['education sector', 'university leadership', 'academic programs', 'faculty coaching', 'higher education'],
    contact_email: 'james.mitchell@wial-usa.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: 'https://jamesmitchellcoaching.com',
    highlight: null,
    total_session_hours: 42,
    total_ce_credits: 10,
  },
  {
    id: '4',
    profile_id: null,
    chapter_id: 'usa',
    chapter_name: 'WIAL USA',
    full_name: 'Priya Sharma',
    photo_url: null,
    certification_level: 'PALC',
    certification_date: '2022-11-20',
    certification_expiry: '2024-11-20',
    bio_raw: 'Tech industry coach in Silicon Valley.',
    bio_enhanced:
      'Priya Sharma is a PALC-certified Action Learning coach embedded in Silicon Valley\'s tech ecosystem. She partners with startup founders, innovation teams, and product leaders to build adaptive problem-solving cultures in fast-paced environments. Priya has worked with over 30 startups and scale-ups across AI, fintech, and SaaS sectors.',
    location_city: 'San Francisco',
    location_country: 'United States',
    specializations: ['technology industry', 'startup leadership', 'innovation teams', 'silicon valley', 'product leadership'],
    contact_email: 'priya.sharma@wial-usa.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: 'https://linkedin.com/in/priyasharma',
    website_url: null,
    highlight: 'I bridge Action Learning methodology with the velocity demands of high-growth tech companies.',
    total_session_hours: 76,
    total_ce_credits: 18,
  },
  {
    id: '5',
    profile_id: null,
    chapter_id: 'nigeria',
    chapter_name: 'WIAL Nigeria',
    full_name: 'Amara Okafor',
    photo_url: null,
    certification_level: 'CALC',
    certification_date: '2023-04-05',
    certification_expiry: '2025-04-05',
    bio_raw: 'Banking and government leadership coach in Lagos.',
    bio_enhanced:
      'Amara Okafor is a CALC-certified Action Learning coach based in Lagos, Nigeria, specializing in banking, financial services, and government agency leadership development. She has partnered with Nigerian public sector institutions and financial institutions to drive leadership transformation and organizational excellence. Amara is passionate about public sector reform and building collaborative leadership cultures within government organizations.',
    location_city: 'Lagos',
    location_country: 'Nigeria',
    specializations: ['banking', 'government agencies', 'public sector', 'leadership development', 'financial services', 'nigerian institutions'],
    contact_email: 'amara.okafor@wialnigeria.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: 'Empowering Nigerian government and banking leaders to solve complex challenges through structured Action Learning.',
    total_session_hours: 55,
    total_ce_credits: 12,
  },
  {
    id: '6',
    profile_id: null,
    chapter_id: 'nigeria',
    chapter_name: 'WIAL Nigeria',
    full_name: 'Emeka Nwosu',
    photo_url: null,
    certification_level: 'PALC',
    certification_date: '2021-08-15',
    certification_expiry: '2023-08-15',
    bio_raw: 'Manufacturing and supply chain coach in Abuja.',
    bio_enhanced:
      'Emeka Nwosu is a PALC-certified Action Learning coach based in Abuja, Nigeria. He specializes in manufacturing sector leadership, supply chain optimization, and operational excellence coaching. Emeka has supported industrial teams across West Africa in building high-performance cultures and solving complex operational challenges through structured reflection.',
    location_city: 'Abuja',
    location_country: 'Nigeria',
    specializations: ['manufacturing', 'supply chain', 'operational excellence', 'industrial teams', 'west africa'],
    contact_email: 'emeka.nwosu@wialnigeria.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: null,
    total_session_hours: 88,
    total_ce_credits: 20,
  },
  {
    id: '7',
    profile_id: null,
    chapter_id: 'nigeria',
    chapter_name: 'WIAL Nigeria',
    full_name: 'Funke Adeyemi',
    photo_url: null,
    certification_level: 'CALC',
    certification_date: '2023-01-12',
    certification_expiry: '2025-01-12',
    bio_raw: 'NGO and community development coach in Lagos.',
    bio_enhanced:
      'Funke Adeyemi is a CALC-certified Action Learning coach in Lagos with a passion for NGO sector leadership and community development. She works with social enterprises, women\'s empowerment organizations, and community-based groups to build leadership capacity and solve systemic challenges. Funke brings a deep commitment to social impact and grassroots leadership development across Nigeria.',
    location_city: 'Lagos',
    location_country: 'Nigeria',
    specializations: ['ngo sector', 'community development', 'social enterprise', "women's empowerment", 'grassroots leadership'],
    contact_email: 'funke.adeyemi@wialnigeria.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: null,
    total_session_hours: 38,
    total_ce_credits: 8,
  },
  {
    id: '8',
    profile_id: null,
    chapter_id: 'brazil',
    chapter_name: 'WIAL Brazil',
    full_name: 'Ana Costa',
    photo_url: null,
    certification_level: 'SALC',
    certification_date: '2020-07-22',
    certification_expiry: '2022-07-22',
    bio_raw: 'Coach corporativo em São Paulo.',
    bio_enhanced:
      'Ana Costa é uma coach SALC certificada em Action Learning, baseada em São Paulo, Brasil. Com vasta experiência em coaching corporativo, ela atua junto a equipes de liderança em multinacionais e grandes empresas brasileiras, promovendo o desenvolvimento organizacional e a cultura de aprendizagem. Ana já trabalhou com mais de 50 organizações nos setores de varejo, manufatura e serviços financeiros.',
    location_city: 'São Paulo',
    location_country: 'Brazil',
    specializations: ['coaching corporativo', 'liderança de equipes', 'desenvolvimento organizacional', 'multinacionais', 'brasil'],
    contact_email: 'ana.costa@wialbrasil.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: 'https://linkedin.com/in/anacosta',
    website_url: null,
    highlight: 'Transformando líderes corporativos através do Action Learning estruturado.',
    total_session_hours: 120,
    total_ce_credits: 28,
  },
  {
    id: '9',
    profile_id: null,
    chapter_id: 'brazil',
    chapter_name: 'WIAL Brazil',
    full_name: 'Ricardo Santos',
    photo_url: null,
    certification_level: 'CALC',
    certification_date: '2023-02-28',
    certification_expiry: '2025-02-28',
    bio_raw: 'Coach do setor público no Rio de Janeiro.',
    bio_enhanced:
      'Ricardo Santos é um coach CALC certificado em Action Learning, especializado no setor governamental e administração pública. Baseado no Rio de Janeiro, ele trabalha com equipes de liderança em agências governamentais, auxiliando no desenvolvimento de líderes para implementação de políticas públicas e transformação institucional. Ricardo tem experiência com órgãos federais, estaduais e municipais.',
    location_city: 'Rio de Janeiro',
    location_country: 'Brazil',
    specializations: ['setor governamental', 'administração pública', 'políticas públicas', 'agências governamentais', 'setor público'],
    contact_email: 'ricardo.santos@wialbrasil.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: null,
    total_session_hours: 45,
    total_ce_credits: 11,
  },
  {
    id: '10',
    profile_id: null,
    chapter_id: 'brazil',
    chapter_name: 'WIAL Brazil',
    full_name: 'Mariana Oliveira',
    photo_url: null,
    certification_level: 'PALC',
    certification_date: '2022-05-18',
    certification_expiry: '2024-05-18',
    bio_raw: 'Coach de saúde em Brasília.',
    bio_enhanced:
      'Mariana Oliveira é uma coach PALC certificada em Action Learning, com foco em gestão de saúde e liderança hospitalar. Baseada em Brasília, ela apoia equipes médicas e gestores do sistema público de saúde no desenvolvimento de habilidades de liderança colaborativa e resolução de problemas complexos. Mariana tem atuado em hospitais universitários e secretarias de saúde em todo o Brasil.',
    location_city: 'Brasília',
    location_country: 'Brazil',
    specializations: ['gestão de saúde', 'liderança hospitalar', 'sistema público de saúde', 'equipes médicas', 'brasília'],
    contact_email: 'mariana.oliveira@wialbrasil.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: null,
    total_session_hours: 67,
    total_ce_credits: 15,
  },
  {
    id: '11',
    profile_id: null,
    chapter_id: 'netherlands',
    chapter_name: 'WIAL Netherlands',
    full_name: 'Twan Paes',
    photo_url: null,
    certification_level: 'MALC',
    certification_date: '2015-03-10',
    certification_expiry: '2027-03-10',
    bio_raw: 'Executive coach with 20+ years in multinationals.',
    bio_enhanced:
      'Twan Paes is a MALC-certified Action Learning coach — the highest certification level — with over 20 years of international experience. Based in Amsterdam, he coaches executive teams in multinational corporations across Europe, focusing on digital transformation, innovation leadership, and cross-cultural team effectiveness. Twan has worked with organizations in 15+ countries across four continents.',
    location_city: 'Amsterdam',
    location_country: 'Netherlands',
    specializations: ['executive coaching', 'multinational corporations', 'digital transformation', 'innovation leadership', 'cross-cultural', 'europe'],
    contact_email: 'twan@wial.nl',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: 'https://linkedin.com/in/twanpaes',
    website_url: 'https://twanpaes.com',
    highlight: 'At the master level, my work is about transforming how organizations learn, adapt, and lead in an uncertain world.',
    total_session_hours: 310,
    total_ce_credits: 72,
  },
  {
    id: '12',
    profile_id: null,
    chapter_id: 'netherlands',
    chapter_name: 'WIAL Netherlands',
    full_name: 'Sophie de Vries',
    photo_url: null,
    certification_level: 'SALC',
    certification_date: '2019-11-05',
    certification_expiry: '2023-11-05',
    bio_raw: 'Public sector and government policy coach in Rotterdam.',
    bio_enhanced:
      'Sophie de Vries is a SALC-certified Action Learning coach based in Rotterdam, specializing in public sector consulting and government policy team leadership. She has coached senior officials across European institutions, national ministries, and municipal governments in the Netherlands, Belgium, and Germany. Sophie is a recognized expert in cross-cultural leadership and institutional change management.',
    location_city: 'Rotterdam',
    location_country: 'Netherlands',
    specializations: ['public sector', 'government policy', 'european institutions', 'cross-cultural leadership', 'institutional change'],
    contact_email: 'sophie.devries@wial.nl',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: 'Bridging policy intent and leadership capability in European government institutions.',
    total_session_hours: 178,
    total_ce_credits: 40,
  },
  {
    id: '13',
    profile_id: null,
    chapter_id: 'netherlands',
    chapter_name: 'WIAL Netherlands',
    full_name: 'Lars Bakker',
    photo_url: null,
    certification_level: 'CALC',
    certification_date: '2023-07-14',
    certification_expiry: '2025-07-14',
    bio_raw: 'University and research team coach in The Hague.',
    bio_enhanced:
      'Lars Bakker is a CALC-certified Action Learning coach based in The Hague, with expertise in higher education and academic research leadership. He works with university faculties, research teams, and academic program directors to build collaborative problem-solving capabilities. Lars has partnered with several Dutch universities and international research institutions to improve cross-disciplinary collaboration.',
    location_city: 'The Hague',
    location_country: 'Netherlands',
    specializations: ['university programs', 'research teams', 'academic leadership', 'higher education', 'the hague'],
    contact_email: 'lars.bakker@wial.nl',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: null,
    total_session_hours: 28,
    total_ce_credits: 6,
  },
  {
    id: '14',
    profile_id: null,
    chapter_id: null,
    chapter_name: 'Unaffiliated',
    full_name: 'Grace Muthoni',
    photo_url: null,
    certification_level: 'CALC',
    certification_date: '2024-01-20',
    certification_expiry: '2026-01-20',
    bio_raw: 'Social enterprise coach in Nairobi.',
    bio_enhanced:
      'Grace Muthoni is a CALC-certified Action Learning coach based in Nairobi, Kenya. She specializes in social enterprise leadership, women\'s empowerment programs, and community-based organizations across East Africa. Grace is passionate about building leadership capacity in grassroots organizations and NGOs that are driving development impact across the region.',
    location_city: 'Nairobi',
    location_country: 'Kenya',
    specializations: ['social enterprise', "women's empowerment", 'community organizations', 'east africa', 'ngos', 'development'],
    contact_email: 'grace.muthoni@wial.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: null,
    total_session_hours: 22,
    total_ce_credits: 4,
  },
  {
    id: '15',
    profile_id: null,
    chapter_id: null,
    chapter_name: 'Unaffiliated',
    full_name: 'David Ochieng',
    photo_url: null,
    certification_level: 'CALC',
    certification_date: '2024-02-08',
    certification_expiry: '2026-02-08',
    bio_raw: 'Hospitality and tourism coach in Mombasa.',
    bio_enhanced:
      'David Ochieng is a CALC-certified Action Learning coach based in Mombasa, Kenya. He works with hospitality and tourism industry leaders, hotel management teams, and service excellence trainers along the Kenyan coast. David brings a unique perspective on team building in multicultural, guest-facing environments and has worked with resorts, safari operators, and coastal hospitality businesses.',
    location_city: 'Mombasa',
    location_country: 'Kenya',
    specializations: ['tourism', 'hospitality', 'team building', 'service excellence', 'coastal kenya', 'mombasa'],
    contact_email: 'david.ochieng@wial.org',
    contact_phone: null,
    is_approved: true,
    embedding: null,
    linkedin_url: null,
    website_url: null,
    highlight: null,
    total_session_hours: 18,
    total_ce_credits: 3,
  },
];

// Simulates the AI semantic search ranking
// In production this calls POST /api/ai/search
export function mockSearch(query: string): typeof MOCK_COACHES {
  const q = query.toLowerCase();

  const KEYWORD_MAP: Record<string, string[]> = {
    government: ['5', '9', '12'],
    governamental: ['5', '9', '12'],
    governamentais: ['5', '9', '12'],
    'public sector': ['5', '9', '12'],
    liderança: ['5', '8', '9'],
    leadership: ['1', '5', '6', '11'],
    banking: ['5'],
    healthcare: ['2', '10'],
    saúde: ['10', '2'],
    education: ['3', '13'],
    technology: ['4'],
    manufacturing: ['6'],
    ngo: ['7', '14'],
    social: ['7', '14'],
    executive: ['1', '11'],
    multinational: ['11', '8'],
    startup: ['4'],
    nigeria: ['5', '6', '7'],
    brazil: ['8', '9', '10'],
    netherlands: ['11', '12', '13'],
    kenya: ['14', '15'],
    hospitality: ['15'],
    research: ['13'],
    university: ['3', '13'],
  };

  const matchedIds = new Set<string>();
  const scoreMap: Record<string, number> = {};

  for (const [keyword, ids] of Object.entries(KEYWORD_MAP)) {
    if (q.includes(keyword)) {
      ids.forEach((id, idx) => {
        matchedIds.add(id);
        scoreMap[id] = (scoreMap[id] ?? 0) + (1 - idx * 0.05);
      });
    }
  }

  if (matchedIds.size === 0) {
    return MOCK_COACHES.map((c) => ({ ...c, similarity: Math.random() * 0.3 + 0.5 }))
      .sort((a, b) => (b.similarity ?? 0) - (a.similarity ?? 0))
      .slice(0, 10);
  }

  const matched = MOCK_COACHES.filter((c) => matchedIds.has(c.id)).map((c) => ({
    ...c,
    similarity: Math.min(0.99, (scoreMap[c.id] ?? 0.5) * 0.9 + 0.05),
  }));

  matched.sort((a, b) => (b.similarity ?? 0) - (a.similarity ?? 0));
  return matched;
}
